// Script to populate second_hand_store table with dummy data
// Run this in your Supabase SQL Editor

-- Clear existing data (optional - comment out if you want to keep existing data)
-- DELETE FROM second_hand_store;

-- Insert comprehensive dummy data for the Second Hand Store
INSERT INTO second_hand_store (
    title, description, price, category, condition, location,
    contact_name, contact_phone, contact_email, image_urls, user_id, is_sold, created_at
) VALUES 
-- Rods & Reels Category
(
    'Shimano Stradic 3000 Spinning Reel',
    'Excellent condition Shimano Stradic 3000 spinning reel. Used only a few times, comes with original box and papers. Perfect for light to medium fishing.',
    850.00,
    'Rods & Reels',
    'Like New',
    'Cape Town',
    'John Smith',
    '082 123 4567',
    'john.smith@email.com',
    ARRAY['/images/placeholder-reel.jpg'],
    'dummy_user_1',
    false,
    NOW() - INTERVAL '30 minutes'
),
(
    'Penn Battle II 4000 Combo',
    'Penn Battle II 4000 reel with 7ft medium action rod. Great for surf fishing and light offshore work. Some minor scratches on reel but functions perfectly.',
    1200.00,
    'Rods & Reels',
    'Good',
    'Durban',
    'Mike Johnson',
    '083 987 6543',
    'mike.j@email.com',
    ARRAY['/images/placeholder-combo.jpg'],
    'dummy_user_2',
    false,
    NOW() - INTERVAL '1 hour'
),
(
    'Daiwa Saltist 4000 Spinning Reel',
    'Daiwa Saltist 4000 spinning reel in excellent condition. Perfect for saltwater fishing, comes with spare spool and original box.',
    2500.00,
    'Rods & Reels',
    'Excellent',
    'Hermanus',
    'Peter van der Merwe',
    '082 111 2222',
    'peter.vdm@email.com',
    ARRAY['/images/placeholder-reel.jpg'],
    'dummy_user_6',
    false,
    NOW() - INTERVAL '20 minutes'
),
(
    'Okuma Ceymar C-30 Spinning Reel',
    'Lightweight Okuma Ceymar C-30 spinning reel. Great for freshwater fishing, very smooth drag system.',
    450.00,
    'Rods & Reels',
    'Good',
    'Stellenbosch',
    'Anna Botha',
    '083 333 4444',
    'anna.botha@email.com',
    ARRAY['/images/placeholder-reel.jpg'],
    'dummy_user_7',
    false,
    NOW() - INTERVAL '30 minutes'
),
(
    'Penn Fierce III 5000 Combo',
    'Penn Fierce III 5000 spinning reel with 8ft heavy action rod. Perfect for surf fishing and light offshore work.',
    1500.00,
    'Rods & Reels',
    'Good',
    'Jeffreys Bay',
    'Johan Pretorius',
    '084 555 6666',
    'johan.p@email.com',
    ARRAY['/images/placeholder-combo.jpg'],
    'dummy_user_8',
    false,
    NOW() - INTERVAL '45 minutes'
),
(
    'Shimano Baitrunner 6000D',
    'Shimano Baitrunner 6000D spinning reel. Excellent for carp and catfish fishing. Includes spare spool and original box.',
    1800.00,
    'Rods & Reels',
    'Excellent',
    'Pretoria',
    'Hendrik van Wyk',
    '082 777 8888',
    'hendrik.vw@email.com',
    ARRAY['/images/placeholder-reel.jpg'],
    'dummy_user_12',
    false,
    NOW() - INTERVAL '15 minutes'
),

-- Tackle & Lures Category
(
    'Assorted Soft Plastics Lures',
    'Collection of 50+ soft plastic lures including paddle tails, jerkbaits, and worms. Various colors and sizes. Great for bass and saltwater fishing.',
    150.00,
    'Tackle & Lures',
    'Good',
    'Port Elizabeth',
    'Sarah Wilson',
    '084 555 1234',
    'sarah.w@email.com',
    ARRAY['/images/placeholder-lures.jpg'],
    'dummy_user_3',
    false,
    NOW() - INTERVAL '2 hours'
),
(
    'Assorted Hard Lures Collection',
    'Collection of 30+ hard lures including poppers, stickbaits, and diving lures. Various brands and colors for different species.',
    800.00,
    'Tackle & Lures',
    'Good',
    'Mossel Bay',
    'Carlos Mendez',
    '085 777 8888',
    'carlos.m@email.com',
    ARRAY['/images/placeholder-lures.jpg'],
    'dummy_user_9',
    false,
    NOW() - INTERVAL '1 hour'
),
(
    'Premium Fishing Line Collection',
    'Assorted fishing lines including braid, fluorocarbon, and monofilament. Various strengths from 4lb to 50lb. All premium brands.',
    300.00,
    'Tackle & Lures',
    'Brand New',
    'Bloemfontein',
    'Maria Ferreira',
    '083 444 5555',
    'maria.f@email.com',
    ARRAY['/images/placeholder-line.jpg'],
    'dummy_user_13',
    false,
    NOW() - INTERVAL '10 minutes'
),
(
    'Saltwater Hook Collection',
    'Large collection of saltwater hooks in various sizes. Includes circle hooks, J-hooks, and treble hooks. Perfect for different species.',
    120.00,
    'Tackle & Lures',
    'Good',
    'East London',
    'James Cooper',
    '084 666 7777',
    'james.c@email.com',
    ARRAY['/images/placeholder-hooks.jpg'],
    'dummy_user_14',
    false,
    NOW() - INTERVAL '25 minutes'
),

-- Electronics Category
(
    'Garmin Striker 4 Fish Finder',
    'Garmin Striker 4 fish finder with GPS. Includes transducer and mounting hardware. Works perfectly, selling due to upgrade.',
    2200.00,
    'Electronics',
    'Excellent',
    'East London',
    'David Brown',
    '082 444 7890',
    'david.brown@email.com',
    ARRAY['/images/placeholder-fishfinder.jpg'],
    'dummy_user_4',
    false,
    NOW() - INTERVAL '1 day'
),
(
    'Lowrance Hook2 4x Fish Finder',
    'Lowrance Hook2 4x fish finder with GPS. Includes transducer and mounting hardware. Great for finding fish.',
    1800.00,
    'Electronics',
    'Good',
    'Knysna',
    'Mark Thompson',
    '087 111 3333',
    'mark.t@email.com',
    ARRAY['/images/placeholder-fishfinder.jpg'],
    'dummy_user_11',
    false,
    NOW() - INTERVAL '2 hours'
),
(
    'Humminbird Helix 5 Fish Finder',
    'Humminbird Helix 5 fish finder with GPS and down imaging. Includes transducer and mounting hardware.',
    2800.00,
    'Electronics',
    'Excellent',
    'Port Elizabeth',
    'Robert Wilson',
    '082 888 9999',
    'robert.w@email.com',
    ARRAY['/images/placeholder-fishfinder.jpg'],
    'dummy_user_15',
    false,
    NOW() - INTERVAL '40 minutes'
),

-- Accessories Category
(
    'Fishing Tackle Box with Tools',
    'Large tackle box with multiple compartments, includes pliers, line cutter, hook remover, and various terminal tackle. Everything you need to get started.',
    300.00,
    'Accessories',
    'Good',
    'Knysna',
    'Lisa Davis',
    '083 222 3456',
    'lisa.davis@email.com',
    ARRAY['/images/placeholder-tacklebox.jpg'],
    'dummy_user_5',
    false,
    NOW() - INTERVAL '2 days'
),
(
    'Fishing Net with Extendable Handle',
    'Large fishing net with telescopic handle extending to 3 meters. Perfect for landing big fish from shore or boat.',
    350.00,
    'Accessories',
    'Excellent',
    'Plettenberg Bay',
    'Sandra van Rensburg',
    '086 999 0000',
    'sandra.vr@email.com',
    ARRAY['/images/placeholder-net.jpg'],
    'dummy_user_10',
    false,
    NOW() - INTERVAL '1.5 hours'
),
(
    'Premium Fishing Chair',
    'Comfortable fishing chair with rod holders and storage pockets. Perfect for long fishing sessions.',
    450.00,
    'Accessories',
    'Like New',
    'Cape Town',
    'Tom Anderson',
    '083 111 2222',
    'tom.a@email.com',
    ARRAY['/images/placeholder-chair.jpg'],
    'dummy_user_16',
    false,
    NOW() - INTERVAL '5 minutes'
),
(
    'Fishing Cooler Box 50L',
    'Large fishing cooler box with wheels and rod holders. Perfect for keeping fish fresh and storing gear.',
    600.00,
    'Accessories',
    'Good',
    'Durban',
    'Patricia Ndlovu',
    '084 333 4444',
    'patricia.n@email.com',
    ARRAY['/images/placeholder-cooler.jpg'],
    'dummy_user_17',
    false,
    NOW() - INTERVAL '35 minutes'
),

-- Clothing & Gear Category
(
    'Fishing Waders and Boots',
    'Neoprene fishing waders with rubber boots. Size Large, excellent condition. Perfect for wading in rivers.',
    400.00,
    'Clothing & Gear',
    'Good',
    'Stellenbosch',
    'Chris de Villiers',
    '082 555 6666',
    'chris.dv@email.com',
    ARRAY['/images/placeholder-waders.jpg'],
    'dummy_user_18',
    false,
    NOW() - INTERVAL '50 minutes'
),
(
    'Fishing Rain Jacket',
    'Waterproof fishing rain jacket with hood. Size Medium, excellent condition. Perfect for rainy fishing days.',
    250.00,
    'Clothing & Gear',
    'Excellent',
    'George',
    'Amanda Botha',
    '083 777 8888',
    'amanda.b@email.com',
    ARRAY['/images/placeholder-jacket.jpg'],
    'dummy_user_19',
    false,
    NOW() - INTERVAL '20 minutes'
),
(
    'Fishing Hat Collection',
    'Collection of 5 fishing hats including bucket hats and caps. Various sizes and colors.',
    150.00,
    'Clothing & Gear',
    'Good',
    'Paarl',
    'Daniel van der Berg',
    '084 999 0000',
    'daniel.vdb@email.com',
    ARRAY['/images/placeholder-hats.jpg'],
    'dummy_user_20',
    false,
    NOW() - INTERVAL '10 minutes'
),

-- Boats & Kayaks Category
(
    'Inflatable Fishing Kayak',
    '2-person inflatable fishing kayak with paddle and pump. Excellent condition, used only a few times.',
    1200.00,
    'Boats & Kayaks',
    'Like New',
    'Somerset West',
    'Gregory Muller',
    '082 111 3333',
    'gregory.m@email.com',
    ARRAY['/images/placeholder-kayak.jpg'],
    'dummy_user_21',
    false,
    NOW() - INTERVAL '1 hour'
),
(
    'Small Fishing Boat Trailer',
    'Small boat trailer suitable for 12-14ft boats. Includes winch and safety chains.',
    800.00,
    'Boats & Kayaks',
    'Good',
    'Gordon''s Bay',
    'Stephan van Niekerk',
    '083 444 5555',
    'stephan.vn@email.com',
    ARRAY['/images/placeholder-trailer.jpg'],
    'dummy_user_22',
    false,
    NOW() - INTERVAL '45 minutes'
),

-- Other Category
(
    'Fishing Books Collection',
    'Collection of 10 fishing books including species guides, techniques, and local fishing spots.',
    200.00,
    'Other',
    'Good',
    'Bellville',
    'Jennifer Smith',
    '084 666 7777',
    'jennifer.s@email.com',
    ARRAY['/images/placeholder-books.jpg'],
    'dummy_user_23',
    false,
    NOW() - INTERVAL '30 minutes'
),
(
    'Fishing License Holder',
    'Waterproof fishing license holder with lanyard. Perfect for keeping your license safe while fishing.',
    50.00,
    'Other',
    'Brand New',
    'Durbanville',
    'Michael van der Walt',
    '082 888 9999',
    'michael.vdw@email.com',
    ARRAY['/images/placeholder-license.jpg'],
    'dummy_user_24',
    false,
    NOW() - INTERVAL '5 minutes'
);

-- Additional 50 items for a total of 74 items
INSERT INTO second_hand_store (
    title, description, price, category, condition, location,
    contact_name, contact_phone, contact_email, image_urls, user_id, is_sold, created_at
) VALUES 
-- Additional Rods & Reels
(
    'Shimano TLD 20/40 Reel',
    'Shimano TLD 20/40 conventional reel. Perfect for big game fishing. Excellent condition with original box.',
    3200.00,
    'Rods & Reels',
    'Excellent',
    'Port Elizabeth',
    'Andre van der Westhuizen',
    '082 999 1111',
    'andre.vdw@email.com',
    ARRAY['/images/placeholder-reel.jpg'],
    'dummy_user_25',
    false,
    NOW() - INTERVAL '12 minutes'
),
(
    'Penn Senator 6/0 Reel',
    'Penn Senator 6/0 conventional reel. Heavy duty for shark and big game fishing.',
    2800.00,
    'Rods & Reels',
    'Good',
    'Durban',
    'Sipho Dlamini',
    '083 222 3333',
    'sipho.d@email.com',
    ARRAY['/images/placeholder-reel.jpg'],
    'dummy_user_26',
    false,
    NOW() - INTERVAL '8 minutes'
),
(
    'Daiwa BG 5000 Spinning Reel',
    'Daiwa BG 5000 spinning reel. Saltwater rated, excellent condition.',
    1600.00,
    'Rods & Reels',
    'Like New',
    'Cape Town',
    'Liam O''Connor',
    '084 444 5555',
    'liam.oc@email.com',
    ARRAY['/images/placeholder-reel.jpg'],
    'dummy_user_27',
    false,
    NOW() - INTERVAL '18 minutes'
),
(
    'Okuma Azores Blue 55 Reel',
    'Okuma Azores Blue 55 spinning reel. Great for offshore fishing.',
    1400.00,
    'Rods & Reels',
    'Good',
    'East London',
    'Thabo Mokoena',
    '082 666 7777',
    'thabo.m@email.com',
    ARRAY['/images/placeholder-reel.jpg'],
    'dummy_user_28',
    false,
    NOW() - INTERVAL '22 minutes'
),
(
    'Shimano FX 2500 Spinning Reel',
    'Shimano FX 2500 spinning reel. Lightweight for freshwater fishing.',
    350.00,
    'Rods & Reels',
    'Excellent',
    'Stellenbosch',
    'Elena van der Berg',
    '083 888 9999',
    'elena.vdb@email.com',
    ARRAY['/images/placeholder-reel.jpg'],
    'dummy_user_29',
    false,
    NOW() - INTERVAL '7 minutes'
),

-- Additional Tackle & Lures
(
    'Premium Jigging Lures Set',
    'Set of 15 premium jigging lures for deep sea fishing. Various weights and colors.',
    450.00,
    'Tackle & Lures',
    'Brand New',
    'Mossel Bay',
    'Johan van Rensburg',
    '084 111 2222',
    'johan.vr@email.com',
    ARRAY['/images/placeholder-lures.jpg'],
    'dummy_user_30',
    false,
    NOW() - INTERVAL '14 minutes'
),
(
    'Carp Fishing Rigs Kit',
    'Complete carp fishing rigs kit with 20 pre-tied rigs and terminal tackle.',
    180.00,
    'Tackle & Lures',
    'Good',
    'Pretoria',
    'Pieter Botha',
    '082 333 4444',
    'pieter.b@email.com',
    ARRAY['/images/placeholder-rigs.jpg'],
    'dummy_user_31',
    false,
    NOW() - INTERVAL '33 minutes'
),
(
    'Saltwater Popper Collection',
    'Collection of 12 saltwater poppers for game fish. Various sizes and colors.',
    280.00,
    'Tackle & Lures',
    'Good',
    'Richards Bay',
    'Nkosi Zulu',
    '083 555 6666',
    'nkosi.z@email.com',
    ARRAY['/images/placeholder-poppers.jpg'],
    'dummy_user_32',
    false,
    NOW() - INTERVAL '19 minutes'
),
(
    'Bass Fishing Crankbaits',
    'Set of 25 bass fishing crankbaits. Various diving depths and colors.',
    320.00,
    'Tackle & Lures',
    'Good',
    'Bloemfontein',
    'Marius Steyn',
    '084 777 8888',
    'marius.s@email.com',
    ARRAY['/images/placeholder-crankbaits.jpg'],
    'dummy_user_33',
    false,
    NOW() - INTERVAL '26 minutes'
),
(
    'Fly Fishing Flies Collection',
    'Collection of 50+ fly fishing flies for trout and bass. Various patterns.',
    200.00,
    'Tackle & Lures',
    'Good',
    'Dullstroom',
    'Sarah Johnson',
    '082 999 0000',
    'sarah.j@email.com',
    ARRAY['/images/placeholder-flies.jpg'],
    'dummy_user_34',
    false,
    NOW() - INTERVAL '11 minutes'
),

-- Additional Electronics
(
    'Raymarine Dragonfly 4 Fish Finder',
    'Raymarine Dragonfly 4 fish finder with GPS. Includes transducer.',
    1900.00,
    'Electronics',
    'Excellent',
    'Knysna',
    'Markus van der Walt',
    '083 111 3333',
    'markus.vdw@email.com',
    ARRAY['/images/placeholder-fishfinder.jpg'],
    'dummy_user_35',
    false,
    NOW() - INTERVAL '16 minutes'
),
(
    'Garmin GPSMAP 64s GPS',
    'Garmin GPSMAP 64s handheld GPS. Perfect for marking fishing spots.',
    1200.00,
    'Electronics',
    'Good',
    'Plettenberg Bay',
    'Andre du Toit',
    '084 444 6666',
    'andre.dt@email.com',
    ARRAY['/images/placeholder-gps.jpg'],
    'dummy_user_36',
    false,
    NOW() - INTERVAL '29 minutes'
),
(
    'VHF Marine Radio',
    'Standard Horizon VHF marine radio with DSC. Essential for boat safety.',
    800.00,
    'Electronics',
    'Good',
    'Hermanus',
    'Willem van der Merwe',
    '082 666 8888',
    'willem.vdm@email.com',
    ARRAY['/images/placeholder-radio.jpg'],
    'dummy_user_37',
    false,
    NOW() - INTERVAL '13 minutes'
),

-- Additional Accessories
(
    'Fishing Rod Holders Set',
    'Set of 4 stainless steel fishing rod holders for boat mounting.',
    400.00,
    'Accessories',
    'Brand New',
    'Gordon''s Bay',
    'Chris van Niekerk',
    '083 888 0000',
    'chris.vn@email.com',
    ARRAY['/images/placeholder-rodholders.jpg'],
    'dummy_user_38',
    false,
    NOW() - INTERVAL '24 minutes'
),
(
    'Fishing Scale 50kg',
    'Digital fishing scale with 50kg capacity. Accurate to 10g.',
    150.00,
    'Accessories',
    'Like New',
    'Somerset West',
    'Lucas Ferreira',
    '084 222 4444',
    'lucas.f@email.com',
    ARRAY['/images/placeholder-scale.jpg'],
    'dummy_user_39',
    false,
    NOW() - INTERVAL '9 minutes'
),
(
    'Fishing Pliers Set',
    'Professional fishing pliers set with line cutter and split ring tool.',
    120.00,
    'Accessories',
    'Good',
    'Paarl',
    'Daniel Botha',
    '082 444 6666',
    'daniel.b@email.com',
    ARRAY['/images/placeholder-pliers.jpg'],
    'dummy_user_40',
    false,
    NOW() - INTERVAL '31 minutes'
),
(
    'Fishing Bucket with Aerator',
    'Large fishing bucket with built-in aerator to keep bait alive.',
    80.00,
    'Accessories',
    'Good',
    'Bellville',
    'Michael van der Berg',
    '083 666 8888',
    'michael.vdb@email.com',
    ARRAY['/images/placeholder-bucket.jpg'],
    'dummy_user_41',
    false,
    NOW() - INTERVAL '17 minutes'
),
(
    'Fishing Rod Rack',
    'Wall-mounted fishing rod rack holds 8 rods securely.',
    200.00,
    'Accessories',
    'Excellent',
    'Durbanville',
    'Peter van Wyk',
    '084 888 0000',
    'peter.vw@email.com',
    ARRAY['/images/placeholder-rodrack.jpg'],
    'dummy_user_42',
    false,
    NOW() - INTERVAL '4 minutes'
),

-- Additional Clothing & Gear
(
    'Fishing Gloves Set',
    'Set of 3 pairs fishing gloves for different weather conditions.',
    100.00,
    'Clothing & Gear',
    'Brand New',
    'George',
    'Amanda van der Walt',
    '082 000 2222',
    'amanda.vdw@email.com',
    ARRAY['/images/placeholder-gloves.jpg'],
    'dummy_user_43',
    false,
    NOW() - INTERVAL '21 minutes'
),
(
    'Fishing Boots Size 10',
    'Waterproof fishing boots size 10. Excellent for wading.',
    350.00,
    'Clothing & Gear',
    'Good',
    'Stellenbosch',
    'Hendrik van der Merwe',
    '083 222 4444',
    'hendrik.vdm@email.com',
    ARRAY['/images/placeholder-boots.jpg'],
    'dummy_user_44',
    false,
    NOW() - INTERVAL '28 minutes'
),
(
    'Fishing Vest with Pockets',
    'Fishing vest with multiple pockets for tackle storage.',
    180.00,
    'Clothing & Gear',
    'Like New',
    'Knysna',
    'Sandra van Rensburg',
    '084 444 6666',
    'sandra.vr@email.com',
    ARRAY['/images/placeholder-vest.jpg'],
    'dummy_user_45',
    false,
    NOW() - INTERVAL '15 minutes'
),
(
    'Fishing Sunglasses Polarized',
    'Polarized fishing sunglasses with UV protection.',
    250.00,
    'Clothing & Gear',
    'Excellent',
    'Plettenberg Bay',
    'Tom van der Berg',
    '082 666 8888',
    'tom.vdb@email.com',
    ARRAY['/images/placeholder-sunglasses.jpg'],
    'dummy_user_46',
    false,
    NOW() - INTERVAL '6 minutes'
),

-- Additional Boats & Kayaks
(
    'Fishing Kayak Paddle',
    'Premium fishing kayak paddle with ergonomic grip.',
    300.00,
    'Boats & Kayaks',
    'Good',
    'Gordon''s Bay',
    'Gregory van Niekerk',
    '083 888 0000',
    'gregory.vn@email.com',
    ARRAY['/images/placeholder-paddle.jpg'],
    'dummy_user_47',
    false,
    NOW() - INTERVAL '23 minutes'
),
(
    'Boat Anchor 5kg',
    '5kg boat anchor with chain and rope. Suitable for small boats.',
    180.00,
    'Boats & Kayaks',
    'Good',
    'Somerset West',
    'Lucas van der Walt',
    '084 000 2222',
    'lucas.vdw@email.com',
    ARRAY['/images/placeholder-anchor.jpg'],
    'dummy_user_48',
    false,
    NOW() - INTERVAL '10 minutes'
),
(
    'Kayak Fishing Rod Holder',
    'Adjustable kayak fishing rod holder for hands-free fishing.',
    120.00,
    'Boats & Kayaks',
    'Brand New',
    'Paarl',
    'Daniel van der Merwe',
    '082 222 4444',
    'daniel.vdm@email.com',
    ARRAY['/images/placeholder-kayakholder.jpg'],
    'dummy_user_49',
    false,
    NOW() - INTERVAL '32 minutes'
),

-- Additional Other Items
(
    'Fishing Magazine Collection',
    'Collection of 20 fishing magazines from the last 2 years.',
    100.00,
    'Other',
    'Good',
    'Bellville',
    'Jennifer van Rensburg',
    '083 444 6666',
    'jennifer.vr@email.com',
    ARRAY['/images/placeholder-magazines.jpg'],
    'dummy_user_50',
    false,
    NOW() - INTERVAL '20 minutes'
),
(
    'Fishing Knot Tying Guide',
    'Comprehensive fishing knot tying guide with practice line.',
    50.00,
    'Other',
    'Brand New',
    'Durbanville',
    'Michael van der Walt',
    '084 666 8888',
    'michael.vdw@email.com',
    ARRAY['/images/placeholder-knotguide.jpg'],
    'dummy_user_51',
    false,
    NOW() - INTERVAL '3 minutes'
),
(
    'Fishing First Aid Kit',
    'Complete fishing first aid kit with bandages and antiseptic.',
    80.00,
    'Other',
    'Brand New',
    'George',
    'Amanda van der Berg',
    '082 888 0000',
    'amanda.vdb@email.com',
    ARRAY['/images/placeholder-firstaid.jpg'],
    'dummy_user_52',
    false,
    NOW() - INTERVAL '25 minutes'
),
(
    'Fishing Log Book',
    'Professional fishing log book to record catches and conditions.',
    40.00,
    'Other',
    'Brand New',
    'Stellenbosch',
    'Hendrik van Rensburg',
    '083 000 2222',
    'hendrik.vr@email.com',
    ARRAY['/images/placeholder-logbook.jpg'],
    'dummy_user_53',
    false,
    NOW() - INTERVAL '12 minutes'
),
(
    'Fishing Weather Station',
    'Portable fishing weather station with wind and pressure sensors.',
    350.00,
    'Other',
    'Good',
    'Knysna',
    'Sandra van der Walt',
    '084 222 4444',
    'sandra.vdw@email.com',
    ARRAY['/images/placeholder-weatherstation.jpg'],
    'dummy_user_54',
    false,
    NOW() - INTERVAL '18 minutes'
);

-- Verify the total data was inserted
SELECT COUNT(*) as total_items FROM second_hand_store;
SELECT category, COUNT(*) as count FROM second_hand_store GROUP BY category ORDER BY count DESC;
